name: increase-tag
on:
  push:
    tags:
      - v*
jobs:

  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v3
        with: 
          images: ghcr.io/skysourced/findtheducks

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
      needs: publish
      name: deploy image
      runs-on: ubuntu-latest
      steps:
        - name: install ssh keys
          run: >
            install -m 600 -D /dev/null ~/.ssh/id_rsa
  
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
  
            ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >
            ~/.ssh/known_hosts

        - name: connect and pull
          run: >-
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -p ${{
            secrets.SSH_PORT }} "cd ${{ secrets.WORK_DIR }} && docker compose pull
            && docker compose up -d && exit"
            
        - name: cleanup
          run: rm -rf ~/.ssh
